### ISSUE TITLE
run error of plasmidtron 0.4.1

### ISSUE THREAD

**Issue by lindechun** [sanger-pathogens/plasmidtron#26]
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

/bin/sh: line 1:  7651 已放弃               kmc_tools -t4 complex traits_config_file > /dev/null 2>&1
Traceback (most recent call last):
  File "/hwfssz1/ST_CANCER/CVD/USER/lindechun/software/anaconda2/envs/py3/bin/plasmidtron", line 46, in <module>
    plasmid_tron.run()
  File "/hwfssz1/ST_CANCER/CVD/USER/lindechun/software/anaconda2/envs/py3/lib/python3.6/site-packages/plasmidtron/PlasmidTron.py", line 244, in run
    kmc_complex.run()
  File "/hwfssz1/ST_CANCER/CVD/USER/lindechun/software/anaconda2/envs/py3/lib/python3.6/site-packages/plasmidtron/KmcComplex.py", line 113, in run
    subprocess.check_call(self.kmc_complex_command('traits_config_file'), shell=True)
  File "/hwfssz1/ST_CANCER/CVD/USER/lindechun/software/anaconda2/envs/py3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'kmc_tools -t4 complex traits_config_file > /dev/null 2>&1' returned non-zero exit status 134.

**Comment by martian-yan** [comment]
I have a similar issue:

`Traceback (most recent call last):
  File "/pub28/yan/miniconda2/envs/bioinfo/bin/plasmidtron", line 46, in <module>
    plasmid_tron.run()
  File "/pub28/yan/miniconda2/envs/bioinfo/lib/python3.6/site-packages/plasmidtron/PlasmidTron.py", line 244, in run
    kmc_complex.run()
  File "/pub28/yan/miniconda2/envs/bioinfo/lib/python3.6/site-packages/plasmidtron/KmcComplex.py", line 113, in run
    subprocess.check_call(self.kmc_complex_command('traits_config_file'), shell=True)
  File "/pub28/yan/miniconda2/envs/bioinfo/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'kmc_tools -t1 complex traits_config_file > /dev/null 2>&1' returned non-zero exit status 1.`

**Comment by samlipworth** [comment]
^ also getting this error

**Comment by shaodongyan** [comment]
^ also getting this error，/root/mcrpec/test2/tmp39voqhol > /dev/null 2>&1' returned non-zero exit status 134.

**Comment by shaodongyan** [comment]
> 学术传统要求您引用文章所依据的作品。
> 当使用使用GNU Parallel处理要发布的数据的程序时，
> 请引用：
> 
> O. Tange（2011）：GNU并行-命令行动力工具
> ；登录：《 USENIX》杂志，2011年2月：42-47。
> 
> 这有助于为进一步发展提供资金；而且不会花费您一分钱。
> 如果您支付10000欧元，则无需引用即可随意使用GNU Parallel。
> 
> 要使此引用通知静音：运行'parallel --citation'。
> 
> / bin / sh：第1行：7651已放弃kmc_tools -t4复杂的traits_config_file> / dev / null 2>＆1
> Traceback（最近一次调用）：
> 文件“ / hwfssz1 / ST_CANCER / CVD / USER / lindechun / software / anaconda2 / envs / py3 / bin / plasmidtron“，第46行，在
> Plasmid_tron.run（）
> 文件中，” / hwfssz1 / ST_CANCER / CVD / USER / lindechun / software / anaconda2 / envs / py3 / lib / python3.6 / site-packages / plasmidtron / 在运行
> kmc_complex.run（）
> 文件的“ /hwfssz1/ST_CANCER/CVD/USER/lindechun/software/anaconda2/envs/py3/lib/python3.6/site-packages/plasmidtron/KmcComplex ”中，第244行的“ PlasmidTron.py”。 py”，第113行，在运行
> subprocess.check_call（self.kmc_complex_command（'traits_config_file'），shell = True）中
> 文件“ /hwfssz1/ST_CANCER/CVD/USER/lindechun/software/anaconda2/envs/py3/lib/python3.6/subprocess.py”，行291，在check_call中
> 引发CalledProcessError（retcode，cmd）
> 子过程。CalledProcessError ：Command' kmc_tools -t4复杂特征config_file> / dev / null 2>＆1'返回了非零退出状态134。

hello，this maybe memory question.

**Comment by kborowsk** [comment]
Hi all, same issue. Has there been any changes or updates with this? 
For context, this is happening for me in the Docker container made with Singularity. Runs for for about an hour on a cloud server, produces multiple output folders and files, then complains with the above error. 

'''
Python 2.7.5
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "C.UTF-8",
	LANG = "en_CA.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "C.UTF-8",
	LANG = "en_CA.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Traceback (most recent call last):
  File "/usr/local/bin/plasmidtron", line 46, in <module>
    plasmid_tron.run()
  File "/usr/local/lib/python3.8/dist-packages/plasmidtron/PlasmidTron.py", line 244, in run
    kmc_complex.run()
  File "/usr/local/lib/python3.8/dist-packages/plasmidtron/KmcComplex.py", line 113, in run
    subprocess.check_call(self.kmc_complex_command('traits_config_file'), shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'kmc_tools -t31 complex traits_config_file > /dev/null 2>&1' returned non-zero exit status 1.
'''

My StdIn is set to 
StdIn=/dev/null
I assume that's not what's causing the issue but it may give some clues. 

Does plasmidtron require some external I/O permissions it's not getting? Would the StdIn setting conflict with code within the subprocess call? The traits_config_file exists and was made (as far as I know) properly. I'm also noting that the others above me had different -t values. Could this call have issues based on number of tasks/threads we set?
